### ISSUE TITLE
admin/qna

### ISSUE THREAD

**Issue by babyybiss** [hi-METAVIRTUAL/Bloom#33]
## Description 

> admin/qna 가 고객 1:1 문의인데 명칭을 주의해서 바꿔야할거같습니다. qna 와 더 어울리는 매칭 질문들이 있어서 쉽게 헷갈릴 수 잇을거같습니다

## Progress

> 어떤 해결책을 원하는지 기술 
-[ ] qna -> customerService 로 변경 하면 좋을거가습니다

**Comment by wjs960** [comment]
테스트

**Comment by jiyeong08** [comment]
customerService로 변경했습니다.
