### ISSUE TITLE
회원가입완료페이지

### ISSUE THREAD

**Issue by wjs960** [hi-METAVIRTUAL/Bloom#45]
## Description 

> description 이러한 상황에서 어쩌구 저쩌구 최대한 자세하게 설명~
http://localhost:8001/regist/memberRegistSuccess
회원가입 완료 문구가 중앙정렬이 안되고 왼쪽으로 쏠려있는것 같은데 확인 부탁드릴게요
그리고 
헤더쪽에 로그아웃 버튼 클릭하면 static 페이지로 이동이 됐는데
루트 페이지로 이동되게 수정 해놓겠습니다.

## Progress

>

-[ 어떤 해결책을 원하는지 기술 

회원가입 완료 문구 중앙정렬  ]
-[ ] 
-[ ] todo3
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by babyybiss** [comment]
문구 중앙정렬 수정 하신걸까요??

**Comment by wjs960** [comment]
수정완료
